name: Harian Fenomena Scraper

on:
  schedule:
    # Berjalan setiap hari pada jam 00:00 UTC (jam 07:00 pagi WIB)
    - cron: '0 0 * * *'
  # Memungkinkan kita memicu script secara manual lewat tombol di web GitHub
  workflow_dispatch: 

jobs:
  scrape-dan-simpan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        cache: 'pip' # Mempercepat proses install library

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Jalankan Scraper Utama
      env:
        # Mengambil kunci rahasia dari brankas GitHub
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python scraper.py